# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.14.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(536, 307)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAutoFillBackground(True)
        self.gain_slider = QSlider(self.centralwidget)
        self.gain_slider.setObjectName(u"gain_slider")
        self.gain_slider.setGeometry(QRect(30, 50, 16, 160))
        self.gain_slider.setMaximum(1000)
        self.gain_slider.setOrientation(Qt.Vertical)
        self.curve_slider = QSlider(self.centralwidget)
        self.curve_slider.setObjectName(u"curve_slider")
        self.curve_slider.setGeometry(QRect(110, 50, 16, 160))
        self.curve_slider.setMaximum(1000)
        self.curve_slider.setOrientation(Qt.Vertical)
        self.run_button = QPushButton(self.centralwidget)
        self.run_button.setObjectName(u"run_button")
        self.run_button.setGeometry(QRect(10, 260, 83, 25))
        self.gain_label = QLabel(self.centralwidget)
        self.gain_label.setObjectName(u"gain_label")
        self.gain_label.setGeometry(QRect(10, 220, 64, 17))
        self.gain_label.setAlignment(Qt.AlignCenter)
        self.curve_label = QLabel(self.centralwidget)
        self.curve_label.setObjectName(u"curve_label")
        self.curve_label.setGeometry(QRect(90, 220, 64, 17))
        self.curve_label.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 31, 17))
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 20, 41, 17))
        self.label_2.setLayoutDirection(Qt.LeftToRight)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(180, 20, 51, 17))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.smooth_slider = QSlider(self.centralwidget)
        self.smooth_slider.setObjectName(u"smooth_slider")
        self.smooth_slider.setGeometry(QRect(190, 50, 16, 160))
        self.smooth_slider.setMinimum(1)
        self.smooth_slider.setMaximum(30)
        self.smooth_slider.setOrientation(Qt.Vertical)
        self.smooth_label = QLabel(self.centralwidget)
        self.smooth_label.setObjectName(u"smooth_label")
        self.smooth_label.setGeometry(QRect(170, 220, 64, 17))
        self.smooth_label.setAlignment(Qt.AlignCenter)
        self.rgb_label = QLabel(self.centralwidget)
        self.rgb_label.setObjectName(u"rgb_label")
        self.rgb_label.setGeometry(QRect(240, 220, 64, 17))
        self.rgb_label.setAlignment(Qt.AlignCenter)
        self.rgb_slider = QSlider(self.centralwidget)
        self.rgb_slider.setObjectName(u"rgb_slider")
        self.rgb_slider.setGeometry(QRect(260, 50, 16, 160))
        self.rgb_slider.setMinimum(0)
        self.rgb_slider.setMaximum(1000)
        self.rgb_slider.setOrientation(Qt.Vertical)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(240, 20, 51, 17))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.video_mix_button = QPushButton(self.centralwidget)
        self.video_mix_button.setObjectName(u"video_mix_button")
        self.video_mix_button.setGeometry(QRect(300, 270, 71, 31))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(300, 20, 71, 17))
        self.label_6.setAlignment(Qt.AlignCenter)
        self.video_mix_label = QLabel(self.centralwidget)
        self.video_mix_label.setObjectName(u"video_mix_label")
        self.video_mix_label.setGeometry(QRect(310, 220, 64, 17))
        self.video_mix_label.setAlignment(Qt.AlignCenter)
        self.video_mix_slider = QSlider(self.centralwidget)
        self.video_mix_slider.setObjectName(u"video_mix_slider")
        self.video_mix_slider.setGeometry(QRect(330, 50, 16, 160))
        self.video_mix_slider.setMinimum(0)
        self.video_mix_slider.setMaximum(1000)
        self.video_mix_slider.setOrientation(Qt.Vertical)
        self.patch_label = QLabel(self.centralwidget)
        self.patch_label.setObjectName(u"patch_label")
        self.patch_label.setGeometry(QRect(410, 220, 64, 17))
        self.patch_label.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(420, 20, 51, 17))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.patch_slider = QSlider(self.centralwidget)
        self.patch_slider.setObjectName(u"patch_slider")
        self.patch_slider.setGeometry(QRect(430, 50, 16, 160))
        self.patch_slider.setMinimum(0)
        self.patch_slider.setMaximum(126)
        self.patch_slider.setOrientation(Qt.Vertical)
        self.patch_button = QPushButton(self.centralwidget)
        self.patch_button.setObjectName(u"patch_button")
        self.patch_button.setGeometry(QRect(400, 240, 71, 51))
        self.video_mix_checkbox = QCheckBox(self.centralwidget)
        self.video_mix_checkbox.setObjectName(u"video_mix_checkbox")
        self.video_mix_checkbox.setGeometry(QRect(300, 240, 85, 21))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.run_button.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.gain_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.curve_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"gain", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"curve", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"smooth", None))
        self.smooth_label.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.rgb_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"rgb", None))
        self.video_mix_button.setText(QCoreApplication.translate("MainWindow", u"Toggle", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"video mix", None))
        self.video_mix_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.patch_label.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"patch", None))
        self.patch_button.setText(QCoreApplication.translate("MainWindow", u"Re-shuffle", None))
        self.video_mix_checkbox.setText(QCoreApplication.translate("MainWindow", u"mix?", None))
    # retranslateUi

